name: moveapps-python-sdk
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=2.0
  - pandas
  - geopandas
  - movingpandas
  - pluggy
  - python-dotenv
  - deprecated
  - matplotlib
  - shapely
  - networkx
  - osmnx
  - overpy
  - folium
  - cython
  - geoviews-core
  - stonesoup
  - geopy
  - spaghetti
  - esda
  - splot
